name: DeadSwap
version: 1.0
api-version: 1.21
main: fr.na.tcharlex.deadswap.Main
commands:
  DSs:
    description: start deadswap
    aliases:
      - dss
    permission: ds.use
  DSog:
    description: change bool OnGame
    permission: ds.use